[package]
name = "led-foot"
version = "0.1.0"
authors = ["Bridger Herman <herma582@umn.edu>"]
edition = "2018"

[dependencies]
lazy_static = "1.2"
png = "0.14"
rustc-serialize = "0.3"
serial = "0.4"
log = "0.4"
simple_logger = "1.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
chrono = "0.4"

actix-rt = "0.2"
actix-web = "1.0.0-beta.3"
actix-files = "0.1.0-beta.1"
actix-session = "0.1.0-beta.2"

futures = "0.1.25"
env_logger = "0.5"
bytes = "0.4"
